'use strict';
const extraTitles={plan:['Correspondance écran → LED.','Visualisez chaque LED et choisissez les couleurs qu’elle doit suivre.'],profiles:['Une ambiance, un clic.','Enregistrez vos éclairages, associations et horaires ensemble.']};
const baseHeader=renderHeader;renderHeader=function(){if(extraTitles[page]){$('page-title').textContent=extraTitles[page][0];$('page-sub').textContent=extraTitles[page][1];$('crumb').textContent=page.toUpperCase();}else baseHeader();};
const baseShow=showPage;showPage=function(p){baseShow(p);if(p==='plan')drawPlan();if(p==='profiles')drawProfiles();};
const baseRoutes=renderRoutes;renderRoutes=function(){baseRoutes();const t=currentTarget();if(t)document.querySelectorAll('[data-route]').forEach((b,i)=>{const r=t.routes[i];if(r?.source&& !['icue','msi','openrgb'].includes(r.source)){b.children[0].textContent=`LED ${r.start}–${r.end}`;b.children[1].textContent=({screen:'Raptor Link · Couleurs écran',audio:'Raptor Link · Réaction audio',rainbow:'Raptor Link · Arc-en-ciel',breathe:'Raptor Link · Respiration',chase:'Raptor Link · Comète',solid:'Raptor Link · Couleur fixe'})[r.source];}else if(r?.source==='msi'){b.children[1].textContent=experimentalEnabled()?'MSI Mystic Light · Expérimental':'Source expérimentale désactivée';}else if(r?.source==='openrgb'){const labels={openrgb:'OpenRGB',msi:'MSI via OpenRGB',gigabyte:'Gigabyte RGB Fusion',asus:'ASUS Aura / Armoury Crate',razer:'Razer Chroma',logitech:'Logitech G HUB',steelseries:'SteelSeries GG / Prism'};b.children[1].textContent=experimentalEnabled()?(labels[r.rgb_ecosystem||'openrgb']||'OpenRGB')+' · Expérimental':'Source expérimentale désactivée';}});};
const baseEditor=renderEditor;renderEditor=function(){baseEditor();if($('zone-source'))fillExtra();};
const baseSettings=settingsUI;settingsUI=function(){baseSettings();if($('fade-in')){const s=config.settings;$('fade-in').value=s.fade_in??3;$('fade-out').value=s.fade_out??2;$('logo-motion').checked=s.logo_animation!==false;}};
const basePreviews=renderPreviews;renderPreviews=function(){basePreviews();const t=currentTarget();if(t&&state.running&&!dirty&&state.frames?.[t.ip])strip($('output-preview'),state.frames[t.ip]);if($('effect-preview')&&t){strip($('effect-preview'),state.frames?.[t.ip]||Array(32).fill([35,65,78]));}};
function defaults(t){t.schedule??={enabled:false,start:'08:00',end:'23:00',mode:'active',days:[0,1,2,3,4,5,6]};t.alarms??=t.alarm?[{...t.alarm,id:'legacy',name:'Réveil 1'}]:[];delete t.alarm;for(const r of t.routes){r.source??='icue';r.brightness??=100;r.offset??=0;r.smooth??=0;r.speed??=1;r.color??=[255,100,20];r.points??=[[.1,.5],[.9,.5]];}}
function field(id,label,type,value,attrs=''){return `<label class="full"><span>${label}</span><input id="${id}" type="${type}" value="${value}" ${attrs}></label>`;}
function days(id,values){return ['L','M','M','J','V','S','D'].map((d,i)=>`<label class="day"><input type="checkbox" data-days="${id}" value="${i}" ${values.includes(i)?'checked':''}><span>${d}</span></label>`).join('');}
function sourceOptions(r){
 const normal=`<optgroup label="Raptor Link & iCUE"><option value="icue">Corsair iCUE — TESTÉ & VALIDÉ</option><option value="screen">Raptor Link — Couleurs de l’écran</option><option value="audio">Raptor Link — Réaction audio</option><option value="rainbow">Raptor Link — Arc-en-ciel</option><option value="breathe">Raptor Link — Respiration</option><option value="chase">Raptor Link — Comète</option><option value="solid">Raptor Link — Couleur fixe</option></optgroup>`;
 let hidden='';
 if(!experimentalEnabled()&&['msi','openrgb'].includes(r?.source))hidden='<option value="__experimental_current" disabled selected>Source expérimentale masquée — activez « laboratoire RGB » dans Réglages</option>';
 const experimental=experimentalEnabled()?`<optgroup label="EXPÉRIMENTAL · LIMITÉ · NON FINALISÉ"><option value="msi">MSI Mystic Light — expérimental</option><option value="openrgb:gigabyte">Gigabyte RGB Fusion — via OpenRGB</option><option value="openrgb:asus">ASUS Aura / Armoury Crate — via OpenRGB</option><option value="openrgb:razer">Razer Chroma — via OpenRGB</option><option value="openrgb:logitech">Logitech G HUB — via OpenRGB</option><option value="openrgb:steelseries">SteelSeries GG / Prism — via OpenRGB</option><option value="openrgb:openrgb">OpenRGB — expérimental</option></optgroup>`:'';
 return hidden+normal+experimental;
}
function fillExtra(){const t=currentTarget(),r=currentRoute();if(!t)return;defaults(t);
$('zone-source').innerHTML=sourceOptions(r);if(!experimentalEnabled()&&['msi','openrgb'].includes(r?.source))$('zone-source').value='__experimental_current';else $('zone-source').value=r?.source==='openrgb'?'openrgb:'+(r.rgb_ecosystem||'openrgb'):(r?.source||'icue');$('zone-bright').value=r?.brightness??100;$('zone-offset').value=r?.offset??0;$('zone-smooth').value=r?.smooth??0;$('zone-speed').value=r?.speed??1;$('zone-color').value='#'+(r?.color||[255,100,20]).map(x=>x.toString(16).padStart(2,'0')).join('');
$('zone-spatial').checked=!!r?.spatial;$('zone-axis').value=r?.axis||'x';
const external=(!r||r.source==='icue'||(experimentalEnabled()&&['msi','openrgb'].includes(r.source)));document.querySelector('.source-panel')?.classList.toggle('local-effect',!external);const deviceLabel=$('source-device')?.closest('label')?.querySelector('span');if(deviceLabel)deviceLabel.textContent=r?.source==='icue'?'Appareil iCUE':(['msi','openrgb'].includes(r?.source)?'Appareil expérimental':'Appareil source');renderRoutes();document.querySelectorAll('.source-panel>.fields,.source-panel>.mode-toolbar,.source-panel>.canvas-wrap,#selection-hint').forEach(e=>e.classList.toggle('hidden',!external));if(!r||r.source==='icue')$('alternate-info').innerHTML='<span class="compat-badge integrated">iCUE · TESTÉ & VALIDÉ</span> Copie les couleurs des LED Corsair vers votre WLED.';else if(r.source==='msi')$('alternate-info').innerHTML=experimentalEnabled()?'<span class="compat-badge testing">EXPÉRIMENTAL · LIMITÉ</span> Mystic Light est encore en développement. Le SDK MSI expose surtout des zones logiques et ne permet pas de recopier correctement toutes les animations adressables.':'<span class="compat-badge testing">SOURCE EXPÉRIMENTALE MASQUÉE</span> Activez le laboratoire RGB dans Réglages avancés pour continuer ce test.';else if(r.source==='openrgb')$('alternate-info').innerHTML=experimentalEnabled()?'<span class="compat-badge testing">EXPÉRIMENTAL · VIA OPENRGB</span> Fonction non finalisée pouvant nécessiter des manipulations supplémentaires.':'<span class="compat-badge testing">SOURCE EXPÉRIMENTALE MASQUÉE</span> Activez le laboratoire RGB dans Réglages avancés pour continuer ce test.';else $('alternate-info').textContent=r.source==='screen'?'Raptor Link prélève directement les couleurs de l’écran suivant votre tracé.':r.source==='audio'?'Raptor Link génère directement les couleurs à partir du son sélectionné dans Réglages.':'Animation générée directement par Raptor Link, sans logiciel RGB tiers.';
$('schedule-enabled').checked=!!t.schedule.enabled;$('schedule-start').value=t.schedule.start;$('schedule-end').value=t.schedule.end;$('schedule-mode').value=t.schedule.mode;$('schedule-days').innerHTML=days('schedule',t.schedule.days);
drawAlarms();drawScreenOptions();
}
function setupExtras(){
 api('window-ready',{}).catch(()=>{});
 document.title='Raptor Link · '+location.port;document.querySelector('.brand').innerHTML='<canvas id="brand-logo" width="160" height="160" aria-label="Logo Raptor"></canvas><div>RAPTOR<span>LINK / PAR VIVIEN</span></div>';
 document.querySelector('header .eyebrow').firstChild.textContent='RAPTOR LINK / ';
 document.querySelector('.side-bottom>span').textContent='VERSION 0.3.14 · BÊTA';
 document.querySelector('.sidebar nav').insertAdjacentHTML('beforeend','<button class="nav" data-page="plan"><b>⌑</b>Correspondance écran → LED</button><button class="nav" data-page="profiles"><b>◐</b>Mes ambiances</button>');
 document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
 document.querySelector('footer').insertAdjacentHTML('beforebegin',`<section id="page-plan" class="page hidden"><div class="panel"><div class="panel-title"><h2 id="plan-heading">Le plan de vos LED</h2><button id="plan-clear" class="secondary">Réinitialiser le tracé</button></div><div id="plan-explanation" class="plan-explanation"></div><div class="button-row"><button id="plan-source-edit" class="secondary">Modifier la source et les écrans</button><label id="plan-screen-toggle" class="check" hidden><input type="checkbox" id="plan-screen-preview">Afficher l’image des écrans en direct</label></div><div id="screen-layout-toolbar" class="screen-layout-toolbar" hidden><label>Action sur le dessin<select id="plan-tool"><option value="led">Dessiner / déplacer les points LED</option><option value="screens">Déplacer les écrans</option></select></label><button id="plan-windows-layout" class="secondary">Reprendre la disposition Windows</button><p class="small muted">La disposition personnalisée s’applique uniquement à cette zone, sans changer Windows.</p><div id="plan-screen-choices"></div></div><div class="plan-workbench"><div class="plan-controls"><div class="fields"><label class="full">1. Zone de LED à représenter<select id="plan-route"></select></label><label class="full">2. Tracé de départ<select id="plan-shape"><option value="line">Ligne horizontale</option><option value="vertical">Ligne verticale</option><option value="desk">Tour du bureau</option><option value="circle">Cercle / logo</option></select></label><button id="plan-apply" class="secondary">Appliquer la forme</button></div><label class="check"><input type="checkbox" id="plan-manual">3. Indiquer le nombre réel de LED entre chaque point</label><div id="plan-segments" class="segment-list"></div><p id="plan-total" class="small"></p><div class="activity-info" id="plan-live-status"></div></div><div class="plan-canvas"><svg id="desk-plan" viewBox="0 0 800 440" aria-label="Plan interactif de l’installation"></svg><p class="muted small">Point orange = départ du tracé. Chaque intervalle contient son propre nombre de LED ; une LED est comptée une seule fois. Les points suivants suivent l’ordre physique du ruban. Les petites pastilles montrent les couleurs produites pour la zone sélectionnée. Survolez une pastille pour son numéro. Un segment à 0 LED représente un passage sans éclairage. Double-cliquez un point pour le retirer (au moins 2 points). Enregistrez pour appliquer.</p></div></div></div></section><section id="page-profiles" class="page hidden"><div class="panel"><div class="panel-title"><h2>Mes profils</h2><button id="profile-new" class="primary">+ Enregistrer l’ambiance actuelle</button></div><p class="muted">Un profil contient les appareils, les zones et leurs horaires. Le démarrage Windows et les préférences générales restent communs.</p><div id="profile-list"></div></div></section>`);
 $('page-lights').insertAdjacentHTML('afterbegin','<div class="raptor-hero"><div><span class="eyebrow">VOTRE ESPACE. VOTRE SIGNATURE.</span><h2>La lumière prend vie.</h2><p>Du clavier au bureau, une même énergie.</p><button id="wizard" class="secondary">✦ Configuration guidée</button></div><canvas id="hero-logo" width="420" height="420" aria-label="Raptor animé"></canvas></div>');
 $('editor').insertAdjacentHTML('afterbegin','<div class="activity-info" id="target-diagnostic"></div>');
 $('probe').parentElement.insertAdjacentHTML('afterend','<button id="test-light" class="link">✦ Tester cet éclairage</button>');
 document.querySelector('.source-panel').insertAdjacentHTML('afterbegin',`<div class="zone-extensions"><label class="full"><span>Source de cette zone</span><select id="zone-source"></select></label><p id="alternate-info" class="small muted"></p><div id="screen-options" hidden><label class="full">Écrans à suivre<select id="screen-mode"><option value="primary">Écran principal Windows</option><option value="all">Tous les écrans réunis</option><option value="custom">Choisir un ou plusieurs écrans</option></select></label><div id="screen-list"></div><button id="screen-refresh" class="link">Actualiser les écrans</button><p class="small muted">Plusieurs écrans forment une surface commune selon leur disposition Windows. Les espaces sans écran restent noirs. Un écran débranché n’est pas remplacé silencieusement.</p></div></div>`);
 document.querySelector('.route-settings').insertAdjacentHTML('beforeend',`<details class="zone-details"><summary>Réglages avancés de la zone</summary>${field('zone-bright','Luminosité de la zone (%)','number',100,'min="0" max="100"')}${field('zone-offset','Décalage (LED)','number',0,'min="-10000" max="10000"')}${field('zone-smooth','Fondu entre couleurs (secondes)','number',0,'min="0" max="60" step="0.1"')}${field('zone-speed','Vitesse de l’effet','number',1,'min="0.05" max="10" step="0.1"')}${field('zone-color','Couleur de l’effet','color','#ff6414')}<p class="small muted">0 = instantané. Exemple : 1 s pour passer du bleu au rose. Si la couleur change avant la fin, le fondu repart de la couleur affichée. Une durée longue adoucit aussi les animations rapides.</p><label class="check"><input id="zone-spatial" type="checkbox">Répartir iCUE selon le plan</label><label class="full">Axe du plan<select id="zone-axis"><option value="x">Horizontal (gauche → droite)</option><option value="y">Vertical (haut → bas)</option></select></label></details>`);
 document.querySelector('.source-panel').insertAdjacentHTML('beforeend','<div class="effect-view"><span class="eyebrow">APERÇU DU FLUX ENVOYÉ</span><div id="effect-preview"></div><p class="muted small">Démarrez la synchronisation pour voir les couleurs. La vitesse, la couleur et le lissage sont dans les réglages avancés de la zone.</p></div>');
 $('editor').insertAdjacentHTML('beforeend',`<div class="settings-grid timing"><div class="panel"><span class="eyebrow">HORAIRES DE CET ÉCLAIRAGE</span><h2>La bonne lumière, au bon moment.</h2><label class="toggle-row">Limiter à une plage horaire<input id="schedule-enabled" type="checkbox" class="switch"></label><div class="fields">${field('schedule-start','De','time','08:00')}${field('schedule-end','À','time','23:00')}</div><label class="full">Pendant cette plage<select id="schedule-mode"><option value="active">Selon l’utilisation du PC</option><option value="always">Allumé en continu, même inactif ou verrouillé</option></select></label><div class="days" id="schedule-days"></div><p class="small muted">En dehors : extinction immédiate prioritaire. Une plage peut traverser minuit. Deux heures identiques = 24 h sur les jours cochés.</p></div><div class="panel"><span class="eyebrow">RÉVEILS LUMINEUX</span><h2>Vos rendez-vous en couleur.</h2><div class="button-row"><button id="alarm-add" class="secondary">+ Ajouter un réveil</button><button id="alarm-delete" class="danger-link">Supprimer</button></div><label class="full">Réveil à modifier<select id="alarm-select"></select></label><div id="alarm-editor">${field('alarm-name','Nom','text','', 'maxlength="60"')}<label class="toggle-row">Activer ce réveil<input id="alarm-enabled" type="checkbox" class="switch"></label><div class="fields">${field('alarm-time','Heure','time','09:00')}${field('alarm-duration','Durée (secondes)','number',30,'min="1" max="3600"')}</div><label class="full">Animation<select id="alarm-effect"><option value="rainbow">Arc-en-ciel</option><option value="breathe">Respiration</option><option value="chase">Comète</option><option value="solid">Blanc chaud / orange</option></select></label><div class="days" id="alarm-days"></div></div><p class="small muted">Chaque réveil possède ses jours, son heure et sa durée. Puis retour au fonctionnement normal. Un nouveau réveil remplace celui en cours ; à heure identique, le dernier de la liste est prioritaire. Respecte les horaires et le verrouillage. Le PC doit être éveillé et la synchronisation lancée ; aucun rattrapage.</p></div></div>`);
 $('page-automation').insertAdjacentHTML('afterbegin',`<div class="panel fade-panel"><span class="eyebrow">TRANSITIONS DOUCES</span><h2>Un réveil en douceur.</h2><div class="fields">${field('fade-in','Fondu à l’allumage / au retour (secondes)','number',3,'min="0" max="60" step="0.5"')}${field('fade-out','Fondu après inactivité (secondes)','number',2,'min="0" max="60" step="0.5"')}</div><p class="small muted">0 = instantané. Les horaires de chaque éclairage se règlent dans sa fiche. Le mode film ignore l’inactivité, jamais la limite horaire. Le PC doit rester allumé pour produire les animations.</p></div>`);
 $('page-automation').insertAdjacentHTML('afterbegin','<div class="activity-info" id="activity-info">Détection de présence…</div>');
 $('page-settings').insertAdjacentHTML('afterbegin',`<div class="settings-grid"><div class="panel"><h2>Votre signature visuelle</h2><label class="toggle-row">Animer le logo arc-en-ciel<input id="logo-motion" type="checkbox" class="switch" checked></label><button id="tutorial-open" class="secondary">Revoir le tutoriel</button><p class="muted small">Raptor Link · Un projet de Vivien Jardot.<br>Votre logo, animé uniquement dans l’interface.</p></div><div class="panel"><h2>Source audio locale</h2><label class="full">Son à analyser<select id="audio-device"><option value="-1">Désactivée</option></select></label><button id="audio-refresh" class="link">Actualiser les appareils</button><p class="muted small">Choisissez directement une sortie (haut-parleurs, casque ou HDMI), ou une entrée microphone. La sortie par défaut est choisie au lancement de la capture. Aucun enregistrement conservé. Active uniquement avec une zone audio synchronisée.<br><meter id="audio-meter" min="0" max="1" value="0"></meter></p><p id="capture-error" class="small"></p></div></div>`);
 $('profile-new').onclick=handle(async()=>{const name=prompt('Nom de l’ambiance (Jeu, Travail, Détente…)');if(!name?.trim())return;config.profiles??=[];if(config.profiles.length>=20)throw Error('20 profils maximum');config.profiles.push({name:name.trim(),targets:structuredClone(config.targets)});mark();await save();drawProfiles();});
 $('test-light').onclick=handle(async()=>{if(dirty)await save();await api('test',{ip:currentTarget().ip});toast('Test demandé : trois secondes de clignotement.');});
 for(const [id,key] of [['zone-bright','brightness'],['zone-offset','offset'],['zone-smooth','smooth'],['zone-speed','speed']])$(id).onchange=()=>{if(currentRoute()){currentRoute()[key]=Number($(id).value);mark();}};
 $('zone-source').onchange=()=>{const r=currentRoute();if(!r)return;const value=$('zone-source').value;if(value==='__experimental_current')return;if(value.startsWith('openrgb:')){r.source='openrgb';r.rgb_ecosystem=value.split(':')[1]||'openrgb';}else if(value==='msi'){r.source='msi';r.rgb_ecosystem='msi';}else{r.source=value;r.rgb_ecosystem='openrgb';}r.device='';r.ids=[];group='all';mark();fillExtra();populateDevices();renderMap();};
 $('zone-spatial').onchange=()=>{if(currentRoute()){currentRoute().spatial=$('zone-spatial').checked;mark();}};
 $('zone-axis').onchange=()=>{if(currentRoute()){currentRoute().axis=$('zone-axis').value;mark();}};
 $('zone-color').oninput=()=>{if(currentRoute()){currentRoute().color=$('zone-color').value.slice(1).match(/../g).map(c=>parseInt(c,16));mark();}};
 for(const kind of ['schedule','alarm'])for(const key of (kind==='schedule'?['enabled','start','end','mode']:['name','enabled','time','duration','effect']))$(`${kind}-${key}`).onchange=()=>{const el=$(`${kind}-${key}`);(kind==='alarm'?currentAlarm():currentTarget().schedule)[key]=key==='enabled'?el.checked:key==='duration'?Number(el.value):el.value;mark();if(kind==='alarm')drawAlarms();};
 document.querySelectorAll('.days').forEach(el=>el.onchange=()=>{const kind=el.id.split('-')[0];(kind==='alarm'?currentAlarm():currentTarget().schedule).days=[...el.querySelectorAll('input:checked')].map(x=>+x.value);mark();});
 for(const [id,key] of [['fade-in','fade_in'],['fade-out','fade_out']])$(id).onchange=()=>{config.settings[key]=Number($(id).value);mark();};
 $('logo-motion').onchange=()=>{config.settings.logo_animation=$('logo-motion').checked;mark();};
 $('audio-device').onchange=()=>{const v=$('audio-device').value;if(v.startsWith('out:')){config.settings.audio_mode='output';config.settings.audio_output=v.slice(4);}else{config.settings.audio_mode='input';config.settings.audio_device=Number(v);}mark();};
 $('screen-refresh').onclick=handle(loadScreens);loadScreens().catch(e=>toast(e.message));
 $('screen-mode').onchange=()=>{const r=currentRoute();if(!r)return;r.screen_ids=$('screen-mode').value==='custom'?(availableScreens[0]?[availableScreens[0].id]:[]):[$('screen-mode').value];mark();drawScreenOptions();};
 $('screen-list').onchange=()=>{const r=currentRoute();if(!r)return;r.screen_ids=[...document.querySelectorAll('#screen-list input:checked')].map(x=>x.value);mark();};
 $('audio-refresh').onclick=handle(loadAudio);loadAudio().catch(e=>toast(e.message));
 $('tutorial-open').onclick=()=>tutorialPrompt();$('wizard').onclick=()=>wizard();
 $('plan-route').onchange=()=>drawPlan(false);$('plan-apply').onclick=()=>{const r=planRoute();if(!r)return;const type=$('plan-shape').value;r.points=type==='desk'?[[.1,.85],[.1,.2],[.9,.2],[.9,.85]]:type==='vertical'?[[.5,.1],[.5,.9]]:type==='circle'?Array.from({length:25},(_,i)=>[.5+.28*Math.cos(i*Math.PI/12),.5+.35*Math.sin(i*Math.PI/12)]):[[.1,.5],[.9,.5]];r.path_counts=null;mark();drawPlan(false);};
 $('plan-clear').onclick=()=>{if(planRoute()){planRoute().points=[[.1,.5],[.9,.5]];planRoute().path_counts=null;mark();drawPlan(false);}};bindPlan();
 $('plan-manual').onchange=()=>{const r=planRoute();if(!r)return;r.path_counts=$('plan-manual').checked?automaticCounts(r):null;mark();drawPlan(false);};
 $('plan-segments').oninput=e=>{const r=planRoute(),i=e.target.dataset.segment;if(!r||i===undefined)return;r.path_counts[+i]=Number(e.target.value);mark();drawPlan(false,true);};
 $('plan-tool').onchange=()=>{drawPlan(false);};
 $('plan-windows-layout').onclick=()=>{const r=planRoute();if(r){r.screen_layout={};mark();drawPlan(false);}};
 $('plan-screen-choices').onchange=()=>{const r=planRoute();if(!r)return;const ids=[...document.querySelectorAll('#plan-screen-choices input:checked')].map(x=>x.value);if(!ids.length){toast('Conservez au moins un écran.');drawPlan(false);return;}r.screen_ids=ids;mark();drawPlan(false);};
 $('plan-source-edit').onclick=()=>{const [ti,ri]=$('plan-route').value.split(':').map(Number);targetIndex=ti;routeIndex=ri;showPage('lights');renderCards();renderEditor();$('zone-source').scrollIntoView({block:'center'});};
 $('plan-screen-preview').onchange=()=>{screenPreviewKey='';clearScreenPreview();refreshScreenPreview();};
 setInterval(updatePlanColors,160);setInterval(refreshScreenPreview,750);
 $('alarm-add').onclick=()=>{const t=currentTarget();if(t.alarms.length>=32){toast('32 réveils maximum par éclairage');return;}t.alarms.push({id:crypto.randomUUID(),name:'Réveil '+(t.alarms.length+1),enabled:true,time:'09:00',duration:30,effect:'rainbow',days:[0,1,2,3,4,5,6]});alarmSelection=t.alarms.at(-1).id;mark();drawAlarms();};
 $('alarm-select').onchange=()=>{alarmSelection=$('alarm-select').value;drawAlarms();};
 $('alarm-delete').onclick=()=>{const t=currentTarget(),a=currentAlarm();if(a&&confirm('Supprimer « '+a.name+' » ?')){t.alarms=t.alarms.filter(x=>x.id!==a.id);mark();drawAlarms();}};
 settingsUI();fillExtra();animateBrand();
 if((config.settings.tutorial||'ask')==='ask')tutorialPrompt();
 setInterval(()=>{if($('target-diagnostic')&&currentTarget()){const t=currentTarget(),seconds=t.idle_seconds??config.settings.idle_seconds;$('target-diagnostic').textContent='État : '+(state.targets[t.ip]||'À l’arrêt')+' · Inactivité détectée : '+(state.idle||0)+' s · Délai appliqué : '+(seconds===0?'désactivé':seconds+' s');}if($('capture-error'))$('capture-error').textContent=state.capture_error||'';if($('audio-meter'))$('audio-meter').value=state.audio_level||0;if($('activity-info'))$('activity-info').textContent='Sans activité détectée : '+(state.idle||0)+' s · Session '+(state.locked?'verrouillée':'active')+' · Bougez la souris : le compteur doit revenir à 0.';},1500);
}
async function loadAudio(){const ds=await api('audio-devices');$('audio-device').innerHTML='<option value="-1">Désactivée</option><optgroup label="Sorties audio — son du PC"><option value="out:default">Sortie Windows par défaut</option>'+(ds.outputs||[]).map(d=>`<option value="out:${esc(d.id)}">${esc(d.name)}</option>`).join('')+'</optgroup><optgroup label="Entrées — microphone / mixage">'+(ds.inputs||[]).map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')+'</optgroup>';const desired=(config.settings.audio_mode||((config.settings.audio_device??-1)>=0?'input':'output'))==='output'?'out:'+(config.settings.audio_output||'default'):String(config.settings.audio_device??-1);if(![...$('audio-device').options].some(o=>o.value===desired))$('audio-device').add(new Option('Appareil enregistré absent',desired));$('audio-device').value=desired;if(ds.error)toast(ds.error);}

function drawProfiles(){$('profile-list').innerHTML=(config.profiles||[]).map((p,i)=>`<div class="profile-card"><div><h2>${esc(p.name)}</h2><p>${p.targets.length} éclairages</p></div><button class="primary" data-load-profile="${i}">Activer</button><button class="danger-link" data-delete-profile="${i}">Supprimer</button></div>`).join('')||'<p class="empty">Enregistrez votre première ambiance.</p>';$('profile-list').onclick=handle(async e=>{if(e.target.dataset.loadProfile!==undefined){if(dirty&&!confirm('Enregistrer les modifications avant de changer de profil ?'))return;if(dirty)await save();await api('profile',{index:+e.target.dataset.loadProfile});config=await api('config');targetIndex=routeIndex=0;renderCards();renderEditor();toast('Ambiance chargée.');}if(e.target.dataset.deleteProfile!==undefined&&confirm('Supprimer ce profil ?')){config.profiles.splice(+e.target.dataset.deleteProfile,1);mark();await save();drawProfiles();}});}
function planRoute(){const [ti,ri]=($('plan-route').value||'').split(':').map(Number);return config.targets[ti]?.routes[ri];}
function automaticCounts(r){const n=r.end-r.start+1,lengths=r.points.slice(1).map((p,i)=>Math.hypot(p[0]-r.points[i][0],p[1]-r.points[i][1])),total=lengths.reduce((a,b)=>a+b,0),weights=lengths.map(v=>total?v/total:1/lengths.length),counts=weights.map(v=>Math.floor(v*n));let left=n-counts.reduce((a,b)=>a+b,0);weights.map((v,i)=>[v*n-counts[i],i]).sort((a,b)=>b[0]-a[0]).slice(0,left).forEach(([,i])=>counts[i]++);return counts;}
function planPositions(r){const n=r.end-r.start+1,pts=r.points,out=[];
 if(r.path_counts){if(r.path_counts.length!==pts.length-1||r.path_counts.some(x=>!Number.isInteger(x)||x<0)||r.path_counts.reduce((a,b)=>a+b,0)!==n)return [];
  r.path_counts.forEach((count,k)=>{for(let i=0;i<count;i++){const f=(i+.5)/count,a=pts[k],b=pts[k+1];out.push([a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]);}});return out;}
 const distances=pts.slice(1).map((p,i)=>Math.hypot(p[0]-pts[i][0],p[1]-pts[i][1])),total=distances.reduce((a,b)=>a+b,0);
 for(let i=0;i<n;i++){let d=total*i/Math.max(1,n-1);for(let k=0;k<distances.length;k++){if(d<=distances[k]||k===distances.length-1){const f=distances[k]?d/distances[k]:0,a=pts[k],b=pts[k+1];out.push([a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]);break;}d-=distances[k];}}return out;}
function drawPlan(rebuild=true,preserveInputs=false){if(rebuild){const value=$('plan-route').value;$('plan-route').innerHTML=config.targets.flatMap((t,ti)=>{defaults(t);return t.routes.map((r,ri)=>`<option value="${ti}:${ri}">${esc(t.name)} / zone ${ri+1}</option>`);}).join('');if([...$('plan-route').options].some(o=>o.value===value))$('plan-route').value=value;}
const selected=planRoute(),canvasHeight=planHeight(selected);$('desk-plan').setAttribute('viewBox',`0 0 800 ${canvasHeight}`);explainPlan(selected);drawScreenChoices(selected);$('desk-plan').classList.toggle('move-screens',selected?.source==='screen'&&$('plan-tool').value==='screens');const planTarget=config.targets[Number(($('plan-route').value||'').split(':')[0])];if(rebuild||planPreviewIp!==planTarget?.ip){planPreviewIp=planTarget?.ip||'';api('plan',{ip:planPreviewIp}).catch(e=>toast(e.message));}$('plan-manual').checked=!!selected?.path_counts;$('plan-manual').disabled=!selected;
if(!preserveInputs)$('plan-segments').innerHTML=selected?.path_counts?selected.path_counts.map((n,i)=>`<label>Points ${i+1} → ${i+2}<input type="number" min="0" max="10000" step="1" data-segment="${i}" value="${n}"><span>LED</span></label>`).join(''):'';
const total=selected?.path_counts?.reduce((a,b)=>a+b,0),expected=selected?selected.end-selected.start+1:0;
$('plan-total').textContent=selected?(total===undefined?`Répartition automatique sur ${expected} LED. Activez le réglage ci-dessus pour renseigner chaque segment.`:`${total} / ${expected} LED réparties`+(total===expected?' — total correct.':' — corrigez le total avant d’enregistrer.')):'Ajoutez d’abord une zone dans Mes éclairages.';
$('plan-total').style.color=total!==undefined&&total!==expected?'#ff926f':'';
let content='<rect x="85" y="65" width="630" height="310" rx="25" fill="#171e27" stroke="#344353"/><rect x="305" y="100" width="190" height="95" rx="8" fill="#0a1017" stroke="#385467"/><rect x="288" y="245" width="225" height="70" rx="8" fill="#202b36" stroke="#4e626e"/><text x="400" y="352" text-anchor="middle" fill="#687d8c">MON ESPACE</text>';
if(selected?.source==='screen')content=screenPlanBackground(selected);
config.targets.forEach(t=>t.routes.forEach(r=>{if(selected?.source==='screen'&&r!==selected)return;const pts=r.points.map(p=>`${p[0]*800},${p[1]*canvasHeight}`).join(' ');content+=`<polyline points="${pts}" fill="none" stroke="${r===selected?'#596776':'#36a9b8'}" stroke-width="${r===selected?2:3}" stroke-linejoin="round" opacity="${r===selected?1:.35}"/>`;}));
if(selected){content+=planPositions(selected).map((p,i)=>`<circle data-plan-led="${i}" cx="${p[0]*800}" cy="${p[1]*canvasHeight}" r="3.2" fill="#586578" stroke="#0a1017" stroke-width=".5"><title>LED ${selected.start+i}</title></circle>`).join('');selected.points.forEach((p,i)=>content+=`<circle data-point="${i}" cx="${p[0]*800}" cy="${p[1]*canvasHeight}" r="9" fill="${i?'#c7fbff':'#ffad53'}" stroke="#07111a" stroke-width="3"/><text pointer-events="none" x="${p[0]*800+12}" y="${p[1]*canvasHeight-12}" fill="#ecf7fb" font-size="12">${i+1}</text>`);}
$('desk-plan').innerHTML=content;screenPreviewKey='';updatePlanColors();refreshScreenPreview();}
function updatePlanColors(){if(page!=='plan'||!$('plan-live-status'))return;const r=planRoute(),ti=Number(($('plan-route').value||'').split(':')[0]),t=config.targets[ti],frame=(t&&state.plan_ip===t.ip?state.plan_frame:null),valid=r&&planPositions(r).length===r.end-r.start+1,live=valid&&state.running&&!dirty&&frame?.length===t.count;
$('plan-live-status').textContent=!r?'Sélectionnez une zone.':!valid?'Répartition à corriger.':dirty?'Modifications non enregistrées : enregistrez puis démarrez pour voir le rendu.':!state.running?'Aperçu arrêté : démarrez la synchronisation.':'Flux produit · '+(state.targets[t.ip]||'En attente')+' · aperçu logiciel, sans confirmation du WLED';
$('desk-plan').querySelectorAll('[data-plan-led]').forEach(el=>{const c=live&&frame[r.start-1+Number(el.dataset.planLed)];el.setAttribute('fill',c?`rgb(${c.join(',')})`:'#586578');});}
function bindPlan(){let drag=null,moved=false,screenDrag=null;const svg=$('desk-plan');function pos(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());return [Math.max(0,Math.min(1,q.x/800)),Math.max(0,Math.min(1,q.y/planHeight(planRoute())))];}svg.onpointerdown=e=>{if(planRoute()?.source==='screen'&&$('plan-tool').value==='screens'){const id=e.target.dataset.screen;if(id){const r=planRoute(),screens=planScreens(r),m=screens.find(s=>s.id===id),bounds=screenBounds(screens);r.screen_layout??={};screens.forEach(s=>r.screen_layout[s.id]=s.rect.slice(0,2));screenDrag={id,x:e.clientX,y:e.clientY,origin:m.rect.slice(0,2),scale:[(bounds[2]-bounds[0])/svg.getBoundingClientRect().width,(bounds[3]-bounds[1])/svg.getBoundingClientRect().height]};svg.setPointerCapture(e.pointerId);}return;}const i=e.target.dataset.point;if(i!==undefined){drag=+i;moved=false;svg.setPointerCapture(e.pointerId);}};svg.onpointermove=e=>{if(screenDrag){const d=screenDrag;planRoute().screen_layout[d.id]=[Math.round(d.origin[0]+(e.clientX-d.x)*d.scale[0]),Math.round(d.origin[1]+(e.clientY-d.y)*d.scale[1])];mark();drawPlan(false);return;}if(drag!==null&&planRoute()){planRoute().points[drag]=pos(e);moved=true;mark();drawPlan(false);}};svg.onpointerup=e=>{if(screenDrag){screenDrag=null;return;}if(planRoute()?.source==='screen'&&$('plan-tool').value==='screens')return;if(e.target.dataset.planLed!==undefined)return;if(drag!==null){drag=null;}else if(!moved&&planRoute()&&planRoute().points.length<64){planRoute().points.push(pos(e));planRoute().path_counts=null;toast('Point ajouté : répartition repassée en automatique.');mark();drawPlan(false);}moved=false;};svg.onpointercancel=()=>{screenDrag=null;drag=null;};svg.ondblclick=e=>{if($('plan-tool').value==='screens'&&planRoute()?.source==='screen')return;const i=e.target.dataset.point;if(i!==undefined&&planRoute().points.length>2){planRoute().points.splice(+i,1);planRoute().path_counts=null;toast('Point retiré : répartition repassée en automatique.');mark();drawPlan(false);}};}
function modal(html){document.querySelector('#extra-dialog')?.remove();const d=document.createElement('dialog');d.id='extra-dialog';d.innerHTML=html;document.body.append(d);d.showModal();return d;}
function tutorialPrompt(){const d=modal('<span class="eyebrow">BIENVENUE DANS RAPTOR LINK</span><h2>Un petit tour ensemble ?</h2><p>Découvrez les appareils, les associations et les automatismes avec des bulles guidées.</p><div class="button-row"><button id="tour-yes" class="primary">Commencer</button><button id="tour-later" class="secondary">Plus tard</button></div><button id="tour-never" class="link">Ne plus proposer au démarrage</button>');$('tour-yes').onclick=()=>{d.close();tour(0);};$('tour-later').onclick=()=>d.close();$('tour-never').onclick=handle(async()=>{await api('tutorial',{value:'never'});config.settings.tutorial='never';d.close();});}
const steps=[['lights','wizard','Ajoutez votre WLED','L’assistant demande son adresse IP, vérifie le nombre de LED puis vous aide à choisir une source.'],['lights','target-cards','Vos éclairages','Chaque fiche peut être activée séparément. Un appareil absent ne bloque pas les autres.'],['lights','editor','Les associations','Choisissez un appareil iCUE puis cliquez une ligne horizontale, verticale ou des LED libres. Chaque zone a sa plage de destination.'],['plan','desk-plan','Où prendre les couleurs ?','Avec une source écran, placez les LED sur les endroits de l’image à suivre. Réglez leur nombre entre les points. Avec iCUE normal ou un effet autonome, ce plan sert à visualiser le ruban.'],['profiles','profile-new','Gardez vos ambiances','Enregistrez vos configurations sous un nom. Vous pourrez les retrouver aussi près de l’horloge Windows.'],['automation','fade-in','Des transitions douces','Réglez les fondus, l’inactivité et le lancement Windows. Les plages horaires et les réveils se règlent dans chaque fiche WLED.'],['settings','tutorial-open','L’aide reste disponible','Vous pouvez toujours relancer ce tutoriel ici.'],['lights','save','Enregistrez, puis démarrez','Enregistrer applique votre configuration au prochain démarrage de la synchronisation. La croix ferme la fenêtre ; Quitter arrête l’application.']];
function tour(i){document.querySelector('.tour-bubble')?.remove();document.querySelector('.tour-focus')?.classList.remove('tour-focus');if(i>=steps.length){api('tutorial',{value:'done'}).catch(()=>{});config.settings.tutorial='done';return;}const [p,id,title,body]=steps[i];showPage(p);const el=$(id);if(el&&el.getClientRects().length){el.classList.add('tour-focus');el.scrollIntoView({block:'center',behavior:'instant'});}const bubble=document.createElement('div');bubble.className='tour-bubble';bubble.setAttribute('role','dialog');bubble.innerHTML=`<span class="eyebrow">DÉCOUVERTE ${i+1} / ${steps.length}</span><h2>${title}</h2><p>${body}</p><div class="button-row"><button id="tour-prev" class="secondary" ${i?'':'disabled'}>Précédent</button><button id="tour-next" class="primary">${i===steps.length-1?'Terminer':'Suivant'}</button></div><button id="tour-stop" class="link">Arrêter le tutoriel</button>`;document.body.append(bubble);$('tour-prev').onclick=()=>tour(i-1);$('tour-next').onclick=()=>tour(i+1);$('tour-stop').onclick=()=>{bubble.remove();document.querySelector('.tour-focus')?.classList.remove('tour-focus');};$('tour-next').focus();}
function wizard(){const d=modal(`<h2>Ajout guidé d’un éclairage</h2><p>Étape 1 — Connectez votre WLED au même réseau que le PC.</p>${field('wiz-ip','Adresse IP du WLED','text','192.168.1.')}<div class="button-row"><button id="wiz-next" class="primary">Vérifier et continuer</button><button id="wiz-cancel" class="secondary">Annuler</button></div><p id="wiz-error"></p>`);$('wiz-cancel').onclick=()=>d.close();$('wiz-next').onclick=handle(async()=>{try{const ip=$('wiz-ip').value.trim();if(config.targets.some(t=>t.ip===ip))throw Error('Cet appareil existe déjà. Ouvrez sa fiche.');const j=await api('probe',{ip});addTarget({ip,name:j.name,count:j.count});d.close();showPage('lights');const next=modal(`<h2>Étape 2 — Votre source</h2><p>${esc(j.name)} : ${j.count} LED détectées. Choisissez une source, puis ajustez la sélection sur la fiche.</p><select id="wiz-source"><option value="rainbow">Arc-en-ciel autonome</option><option value="screen">Couleurs de l’écran</option>${state.devices.filter(x=>experimentalEnabled()||(x.provider||'icue')==='icue').map(x=>`<option value="${esc(x.id)}">${esc(x.model)}</option>`).join('')}</select><button id="wiz-finish" class="primary">Configurer cette source</button>`);$('wiz-finish').onclick=()=>{const v=$('wiz-source').value,r=currentRoute();if(['rainbow','screen'].includes(v))r.source=v;else{r.source='icue';r.device=v;const device=state.devices.find(d=>d.id===v);r.source=experimentalEnabled()?(device?.provider==='msi'?'msi':device?.provider==='openrgb'?'openrgb':'icue'):'icue';r.rgb_ecosystem=device?.provider==='openrgb'?deviceEcosystem(device):r.source==='msi'?'msi':'openrgb';r.device_model=device?.model||'';r.device_serial=device?.serial||'';r.ids=[];}mark();renderEditor();next.close();toast(['icue','msi','openrgb'].includes(r.source)?'Étape 3 : cliquez les LED à copier, puis Enregistrer et Démarrer.':'Vérifiez l’aperçu, puis Enregistrer et Démarrer.');};}catch(e){$('wiz-error').textContent=e.message;}});}
// Preserve the original geometry. Animate only the colored connected pieces in canvas.
async function animateBrand(){try{const response=await fetch('/logo.svg');if(!response.ok)throw Error('Logo indisponible');const doc=new DOMParser().parseFromString(await response.text(),'image/svg+xml');for(const id of ['hero-logo','brand-logo']){const old=$(id);if(old){const svg=document.importNode(doc.documentElement,true);svg.id=id;old.replaceWith(svg);}}const update=()=>document.querySelectorAll('.raptor-logo').forEach(svg=>svg.classList.toggle('is-static',config?.settings.logo_animation===false));update();setInterval(update,250);}catch(e){toast(e.message);}}

function hsl(h,s,l){const a=s*Math.min(l,1-l),f=n=>{const k=(n+h/30)%12;return 255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)));};return [f(0),f(8),f(4)];}
const boot=setInterval(()=>{if(config&&$('source-device').onchange){clearInterval(boot);setupExtras();}},50);

let alarmSelection=null;
function currentAlarm(){const alarms=currentTarget()?.alarms||[];return alarms.find(a=>a.id===alarmSelection)||alarms[0];}
function drawAlarms(){const alarms=currentTarget()?.alarms||[],a=currentAlarm();alarmSelection=a?.id||null;$('alarm-select').innerHTML=alarms.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.time)}${x.enabled?'':' · désactivé'}</option>`).join('')||'<option>Aucun réveil</option>';$('alarm-select').value=alarmSelection||'';$('alarm-editor').hidden=!a;$('alarm-delete').disabled=!a;if(!a)return;$('alarm-name').value=a.name;$('alarm-enabled').checked=a.enabled;$('alarm-time').value=a.time;$('alarm-duration').value=a.duration;$('alarm-effect').value=a.effect;$('alarm-days').innerHTML=days('alarm',a.days);}

let availableScreens=[],planPreviewIp='';
async function loadScreens(){availableScreens=(await api('screens')).screens;drawScreenOptions();if(page==='plan')drawPlan(false);}
function drawScreenOptions(){const r=currentRoute();if(!$('screen-options'))return;$('screen-options').hidden=r?.source!=='screen';if(!r)return;const ids=r.screen_ids||['primary'],special=ids.length===1&&['primary','all'].includes(ids[0]);$('screen-mode').value=special?ids[0]:'custom';$('screen-list').hidden=special;const list=availableScreens.concat(ids.filter(id=>!['primary','all'].includes(id)&&!availableScreens.some(m=>m.id===id)).map(id=>({id,name:id+' · déconnecté'})));$('screen-list').innerHTML=list.map(m=>`<label class="check"><input type="checkbox" value="${esc(m.id)}" ${ids.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('')||'<p>Aucun écran détecté. Cliquez sur Actualiser.</p>';}
function planScreens(r){const ids=r.screen_ids||['primary'];return availableScreens.filter(m=>ids.includes('all')||(ids.includes('primary')&&m.primary)||ids.includes(m.id)).map(m=>{const [x,y,b,c]=m.rect,[l,t]=r.screen_layout?.[m.id]||[x,y];return {...m,rect:[l,t,l+b-x,t+c-y]};});}
function screenBounds(screens){return [Math.min(...screens.map(m=>m.rect[0])),Math.min(...screens.map(m=>m.rect[1])),Math.max(...screens.map(m=>m.rect[2])),Math.max(...screens.map(m=>m.rect[3]))];}
function drawScreenChoices(r){$('screen-layout-toolbar').hidden=r?.source!=='screen';if(r?.source!=='screen')return;const selected=planScreens(r);$('plan-screen-choices').innerHTML=availableScreens.map(m=>`<label class="check"><input type="checkbox" value="${esc(m.id)}" ${selected.some(s=>s.id===m.id)?'checked':''}>${esc(m.name)}</label>`).join('');}
function planHeight(r){if(r?.source!=='screen')return 440;const s=planScreens(r);if(!s.length)return 440;const [l,t,b,c]=screenBounds(s);return 800*(c-t)/(b-l);}
function screenPlanBackground(r){const canvasHeight=planHeight(r),screens=planScreens(r);if(!screens.length)return '<text x="30" y="40" fill="#ffad53">Écran absent : actualisez la liste dans la fiche de la zone.</text>';const [left,top,right,bottom]=screenBounds(screens);return `<image id="plan-screen-image" x="0" y="0" width="800" height="${canvasHeight}" preserveAspectRatio="none"/>`+screens.map(m=>{const [x,y,b,c]=m.rect,l=(x-left)*800/(right-left),t=(y-top)*canvasHeight/(bottom-top),w=(b-x)*800/(right-left),h=(c-y)*canvasHeight/(bottom-top);return `<rect data-screen="${esc(m.id)}" class="screen-surface" x="${l}" y="${t}" width="${w}" height="${h}" fill="#141e29" stroke="#8297aa" stroke-width="2"/><text pointer-events="none" x="${l+12}" y="${t+30}" fill="#eef7ff" stroke="#101820" stroke-width="3" paint-order="stroke" font-size="13">${esc(m.name)}</text>`;}).join('');}

let screenPreviewBusy=false,screenPreviewKey='';
function explainPlan(r){const screen=r?.source==='screen',spatial=['icue','msi','openrgb'].includes(r?.source)&&r.spatial;$('plan-heading').textContent=screen?'Où prendre les couleurs de l’écran ?':spatial?'Quelles touches suivent vos LED ?':'Visualisez la forme de vos LED';$('plan-screen-toggle').hidden=!screen;$('plan-source-edit').disabled=!r;
$('plan-explanation').innerHTML=screen?'<span class="eyebrow">VOS ÉCRANS → LES COULEURS DE VOS LED</span><p><strong>Une pastille = une LED. Placez-la sur la partie de l’image dont elle doit copier la couleur.</strong><br>À gauche du dessin → couleurs à gauche de l’écran. Déplacez les gros points pour ajuster le tracé.</p><details><summary>Comprendre le plan</summary><p class="small muted">Choisissez une zone, ses écrans, puis son tracé. Les écrans suivent leur disposition Windows. Le tracé peut longer les bords ou traverser le centre, selon les couleurs à prélever. Vous n’êtes pas obligé de reproduire la forme physique du bureau. Cochez l’image en direct, avec la synchronisation lancée, pour vous repérer.</p></details>' :spatial?`<span class="eyebrow">SOURCE : RGB PC · RÉPARTITION PAR POSITION</span><p>Les positions sur le plan choisissent parmi les LED RGB sélectionnées, suivant l’axe horizontal ou vertical réglé dans la zone. <strong>Les couleurs viennent de ${r?.source==='msi'?'MSI Mystic Light natif':r?.source==='openrgb'?'la source RGB Bêta via OpenRGB':'iCUE'}.</strong> Le plan affiche ensuite le résultat pour chaque LED du ruban.</p>`:'<span class="eyebrow">APERÇU DE LA FORME DU RUBAN</span><p><strong>Le dessin vous permet de voir vos LED à leur place.</strong> Avec cette source, déplacer le tracé ne change pas les couleurs : elles suivent votre association iCUE ou votre effet. Pour prélever les couleurs d’un écran, choisissez la source « Couleurs d’un ou plusieurs écrans ».</p>';
}
function clearScreenPreview(){$('plan-screen-image')?.removeAttribute('href');document.querySelectorAll('.screen-surface').forEach(e=>e.setAttribute('fill','#141e29'));}
async function refreshScreenPreview(){if(screenPreviewBusy||page!=='plan')return;const r=planRoute();if(r?.source!=='screen'||!$('plan-screen-preview').checked||!state.running||state.locked||dirty){clearScreenPreview();return;}const ids=r.screen_ids||['primary'],layout=r.screen_layout||{},key=JSON.stringify([ids,layout]);screenPreviewBusy=true;try{const reply=await api('screen-preview',{ids,layout});const current=planRoute();if(page==='plan'&&current?.source==='screen'&&JSON.stringify([current.screen_ids||['primary'],current.screen_layout||{}])===key&&$('plan-screen-preview').checked&&!dirty){if(reply.image){$('plan-screen-image')?.setAttribute('href',reply.image);document.querySelectorAll('.screen-surface').forEach(e=>e.setAttribute('fill','transparent'));screenPreviewKey=key;}else{clearScreenPreview();$('plan-live-status').textContent=reply.reason||'Image écran indisponible.';}}}catch(e){clearScreenPreview();}finally{screenPreviewBusy=false;}}
